# Generated by Django 3.0.5 on 2020-04-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='images',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
