# Generated by Django 3.0.5 on 2020-04-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_app', '0004_auto_20200420_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(max_length=200),
        ),
    ]
